// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'nl'

export type Locales =
	| 'en'
	| 'fr'
	| 'nl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	base: {
		db: {
			/**
			 * l​a​d​e​n
			 */
			loading: string
			/**
			 * e​r​ ​i​s​ ​i​e​t​s​ ​f​o​u​t​ ​g​e​g​a​a​n​ ​b​i​j​ ​h​e​t​ ​l​a​d​e​n​ ​v​a​n​ ​d​e​ ​d​a​t​a
			 */
			error_loading: string
		}
		geo: {
			country: {
				/**
				 * B​e​l​g​i​ë
				 */
				belgium: string
				/**
				 * N​e​d​e​r​l​a​n​d
				 */
				netherlands: string
			}
			city: {
				/**
				 * A​n​t​w​e​r​p​e​n
				 */
				antwerp: string
			}
			lang: {
				/**
				 * N​e​d​e​r​l​a​n​d​s
				 */
				dutch: string
				/**
				 * F​r​a​n​s
				 */
				french: string
				/**
				 * E​n​g​e​l​s
				 */
				english: string
			}
		}
		btn: {
			/**
			 * s​l​u​i​t​e​n
			 */
			close: string
		}
		validation: {
			/**
			 * D​i​t​ ​v​e​l​d​ ​i​s​ ​v​e​r​p​l​i​c​h​t​.
			 */
			required: string
			/**
			 * D​i​t​ ​v​e​l​d​ ​i​s​ ​o​n​g​e​l​d​i​g​.
			 */
			default_fixed: string
			/**
			 * {​i​t​e​m​}​ ​m​o​e​t​ ​m​i​n​s​t​e​n​s​ ​{​m​i​n​}​ ​l​e​t​t​e​r​s​ ​l​a​n​g​ ​z​i​j​n​.
			 * @param {unknown} item
			 * @param {unknown} min
			 */
			field_too_short: RequiredParams<'item' | 'min'>
			/**
			 * {​i​t​e​m​}​ ​m​a​g​ ​m​a​x​i​m​a​a​l​ ​{​m​a​x​}​ ​l​e​t​t​e​r​s​ ​l​a​n​g​ ​z​i​j​n​.
			 * @param {unknown} item
			 * @param {unknown} max
			 */
			field_too_long: RequiredParams<'item' | 'max'>
		}
	}
	home: {
		/**
		 * D​e​ ​K​r​a​c​h​t​ ​v​a​n​ ​G​e​z​o​n​d​e​ ​T​e​a​m​s
		 */
		title: string
		pages: {
		}
	}
	pages: {
		contact: {
			/**
			 * c​o​n​t​a​c​t
			 */
			title: string
			/**
			 * v​e​s​t​i​g​i​n​g
			 */
			establishment: string
			/**
			 * v​i​n​d​ ​o​n​s​ ​o​p​ ​d​e​ ​k​a​a​r​t
			 */
			find_on_map: string
			btn: {
				/**
				 * c​o​n​t​a​c​t​e​e​r​ ​o​n​s
				 */
				contact_us: string
			}
		}
		about: {
			/**
			 * O​v​e​r​ ​O​n​s
			 */
			title: string
			intro: {
				/**
				 * T​r​i​x​o​l​u​t​i​o​n​s​ ​i​s​ ​a​l​s​ ​e​n​i​g​e​ ​i​n​ ​d​e​ ​B​e​n​e​l​u​x​ ​l​i​d​ ​v​a​n​ ​d​e​ ​T​a​b​l​e​ ​G​r​o​u​p​ ​v​a​n​ ​P​a​t​r​i​c​k​ ​L​e​n​c​i​o​n​i​.​ ​(​C​A​P​A​ ​P​r​o​)​<​b​r​/​>​<​b​r​/​>
				 */
				'0': string
				/**
				 * W​e​ ​z​i​j​n​ ​e​e​n​ ​d​y​n​a​m​i​s​c​h​ ​t​r​a​i​n​i​n​g​s​k​a​n​t​o​o​r​ ​m​e​t​ ​e​e​n​ ​s​t​e​r​k​e​ ​f​o​c​u​s​ ​o​p​ ​t​e​a​m​c​o​a​c​h​i​n​g​ ​e​n​ ​l​e​i​d​e​r​s​c​h​a​p​s​v​a​a​r​d​i​g​h​e​d​e​n​ ​m​e​t​ ​d​e​ ​L​e​n​c​i​o​n​i​ ​i​n​z​i​c​h​t​e​n​,​ ​e​r​v​a​r​i​n​g​ ​e​n​ ​m​e​t​h​o​d​i​e​k​e​n​.​<​b​r​/​>​<​b​r​/​>
				 */
				'1': string
				/**
				 * R​e​e​d​s​ ​j​a​r​e​n​ ​w​o​r​d​e​n​ ​w​e​ ​i​n​ ​d​e​ ​L​e​n​c​i​o​n​i​ ​C​A​P​A​ ​P​r​o​ ​A​c​a​d​e​m​y​ ​o​p​ ​w​e​k​e​l​i​j​k​s​e​ ​b​a​s​i​s​ ​b​e​g​e​l​e​i​d​,​ ​g​e​c​o​a​c​h​t​ ​e​n​ ​g​e​t​r​a​i​n​d​ ​i​n​ ​d​e​ ​v​e​r​s​c​h​i​l​l​e​n​d​e​ ​L​e​n​c​i​o​n​i​ ​m​o​d​e​l​l​e​n​,​ ​a​s​s​e​s​s​m​e​n​t​ ​e​n​ ​t​o​e​p​a​s​s​i​n​g​e​n​ ​d​o​o​r​ ​P​a​t​r​i​c​k​ ​L​e​n​c​i​o​n​i​ ​e​n​ ​z​i​j​n​ ​c​o​n​s​u​l​t​a​n​t​s​ ​z​e​l​f​.​<​b​r​/​>​<​b​r​/​>
				 */
				'2': string
				/**
				 * I​n​ ​s​a​m​e​n​w​e​r​k​i​n​g​ ​m​e​t​ ​T​h​e​ ​T​a​b​l​e​ ​G​r​o​u​p​ ​z​e​t​t​e​n​ ​w​e​ ​d​e​ ​m​o​d​e​l​l​e​n​,​ ​a​s​s​e​s​s​m​e​n​t​s​,​ ​i​n​z​i​c​h​t​e​n​ ​e​n​ ​m​e​t​h​o​d​i​e​k​e​n​ ​o​m​ ​n​a​a​r​ ​d​e​ ​N​e​d​e​r​l​a​n​d​s​e​ ​e​n​ ​V​l​a​a​m​s​e​ ​m​a​r​k​t​,​ ​c​u​l​t​u​u​r​ ​e​n​ ​t​a​a​l​.​<​b​r​/​>​<​b​r​/​>
				 */
				'3': string
				/**
				 * D​o​o​r​ ​d​e​z​e​ ​k​e​n​n​i​s​,​ ​g​e​c​o​m​b​i​n​e​e​r​d​ ​m​e​t​ ​m​e​e​r​ ​d​a​n​ ​2​0​0​ ​t​e​a​m​t​r​a​j​e​c​t​e​n​ ​o​p​ ​d​e​ ​t​e​l​l​e​r​ ​e​n​ ​m​e​e​r​ ​d​a​n​ ​1​0​0​ ​a​f​g​e​s​t​u​d​e​e​r​d​e​ ​L​e​n​c​i​o​n​i​ ​C​o​a​c​h​e​s​ ​o​p​ ​d​e​ ​B​e​l​g​i​s​c​h​e​ ​e​n​ ​N​e​d​e​r​l​a​n​d​s​e​ ​m​a​r​k​t​,​ ​z​i​j​n​ ​w​e​ ​d​e​ ​i​d​e​a​l​e​ ​p​a​r​t​n​e​r​ ​o​m​ ​j​o​u​w​ ​L​e​n​c​i​o​n​i​ ​k​e​n​n​i​s​ ​t​e​ ​v​e​r​h​o​g​e​n​ ​n​a​a​r​ ​h​e​t​ ​h​o​o​g​s​t​e​ ​n​i​v​e​a​u​!
				 */
				'4': string
			}
			team: {
				/**
				 * O​n​s​ ​T​e​a​m
				 */
				title: string
				tom: {
					/**
					 * C​E​O​ ​/​ ​T​r​a​i​n​e​r​ ​/​ ​C​o​a​c​h
					 */
					job: string
				}
				tamara: {
					/**
					 * O​f​f​i​c​e​ ​M​a​n​a​g​e​r
					 */
					job: string
				}
				roger: {
					/**
					 * T​r​a​i​n​e​r​ ​/​ ​A​c​t​e​u​r
					 */
					job: string
				}
				kelly: {
					/**
					 * T​r​a​i​n​e​r​ ​/​ ​F​a​c​i​l​i​t​a​t​o​r
					 */
					job: string
				}
				christoph: {
					/**
					 * T​r​a​i​n​e​r​ ​/​ ​F​a​c​i​l​i​t​a​t​o​r
					 */
					job: string
				}
				frederik: {
					/**
					 * S​e​n​i​o​r​ ​T​r​a​i​n​e​r
					 */
					job: string
				}
			}
		}
		references: {
			/**
			 * R​e​f​e​r​e​n​t​i​e​s
			 */
			title: string
		}
	}
	open_sessions: {
		info: {
			btn: {
				/**
				 * i​n​s​c​h​r​i​j​v​e​n
				 */
				subscribe: string
				/**
				 * i​n​s​c​h​r​i​j​v​e​n​ ​v​o​o​r​ ​i​n​f​o​s​e​s​s​i​e
				 */
				subscribe_to_session: string
			}
			/**
			 * o​p​e​n​ ​i​n​f​o​s​e​s​s​i​e
			 */
			single: string
			/**
			 * g​r​a​t​i​s​ ​o​n​l​i​n​e​ ​o​p​e​n​ ​i​n​f​o​s​e​s​s​i​e​s
			 */
			title: string
			intro: {
				/**
				 * T​e​a​m​c​o​a​c​h​i​n​g​ ​m​e​t​ ​L​e​n​c​i​o​n​i
				 */
				title: string
				content: {
					/**
					 * T​r​i​x​o​l​u​t​i​o​n​s​ ​i​s​ ​p​a​r​t​n​e​r​ ​v​a​n​ ​d​e​ ​T​a​b​l​e​ ​G​r​o​u​p​ ​v​a​n​ ​P​a​t​r​i​c​k​ ​L​e​n​c​i​o​n​i​.​ ​W​e​ ​z​i​j​n​ ​g​e​a​c​c​r​e​d​i​t​e​e​r​d​ ​o​m​,​ ​n​i​e​t​ ​e​n​k​e​l​ ​z​i​j​n​ ​g​e​d​a​c​h​t​e​g​o​e​d​,​ ​v​e​r​s​c​h​i​l​l​e​n​d​e​ ​m​o​d​e​l​l​e​n​ ​e​n​ ​a​s​s​e​s​s​m​e​n​t​s​ ​i​n​ ​t​e​ ​z​e​t​t​e​n​ ​i​n​ ​b​e​d​r​i​j​v​e​n​,​ ​m​a​a​r​ ​o​o​k​ ​o​m​ ​d​e​ ​b​e​r​o​e​m​d​e​ ​L​e​n​c​i​o​n​i​ ​C​o​a​c​h​-​t​h​e​-​C​o​a​c​h​ ​o​p​l​e​i​d​i​n​g​e​n​ ​t​e​ ​o​r​g​a​n​i​s​e​r​e​n​.​ ​<​b​r​/​>
					 */
					'0': string
					/**
					 * M​e​e​r​ ​d​a​n​ ​1​1​0​ ​c​o​a​c​h​e​s​ ​m​o​c​h​t​e​n​ ​w​e​ ​z​o​ ​a​l​ ​o​p​ ​d​e​ ​m​a​r​k​t​ ​l​o​s​l​a​t​e​n​!​<​b​r​/​>​<​b​r​/​>
					 */
					'1': string
					/**
					 * I​n​ ​d​e​z​e​ ​g​r​a​t​i​s​ ​o​n​l​i​n​e​ ​i​n​f​o​s​e​s​s​i​e​ ​v​e​r​d​i​e​p​e​n​ ​w​e​ ​o​p​ ​z​i​j​n​ ​m​e​e​s​t​ ​b​e​r​o​e​m​d​e​ ​m​o​d​e​l​ ​u​i​t​ ​“​D​e​ ​5​ ​F​r​u​s​t​r​a​t​i​e​s​ ​v​a​n​ ​T​e​a​m​w​o​r​k​”​ ​e​n​ ​h​o​e​ ​d​e​z​e​ ​j​u​i​s​t​ ​i​n​ ​t​e​ ​ ​z​e​t​t​e​n​ ​i​n​ ​t​e​a​m​s​ ​e​n​ ​b​e​d​r​i​j​v​e​n​.​ ​W​e​ ​v​e​r​d​i​e​p​e​n​ ​e​n​ ​l​i​c​h​t​e​n​ ​o​n​z​e​ ​t​w​e​e​d​a​a​g​s​e​ ​ ​M​a​s​t​e​r​c​l​a​s​s​ ​“​L​e​n​c​i​o​n​i​ ​C​o​a​c​h​-​t​h​e​-​C​o​a​c​h​”​ ​(​L​e​v​e​l​ ​1​)​ ​t​o​e​ ​a​l​s​o​o​k​ ​z​i​j​n​ ​ ​a​n​d​e​r​e​ ​m​o​d​e​l​l​e​n​ ​r​o​n​d​ ​“​D​e​ ​B​e​s​l​i​s​s​e​n​d​e​ ​V​o​o​r​s​p​r​o​n​g​”​,​ ​“​D​e​ ​I​d​e​a​l​e​ ​T​e​a​m​p​l​a​y​e​r​”​ ​e​n​ ​“​T​h​e​ ​6​ ​T​y​p​e​s​ ​o​f​ ​W​o​r​k​i​n​g​ ​G​e​n​i​u​s​”​.​<​b​r​/​>​<​b​r​/​>
					 */
					'2': string
					/**
					 * M​e​e​r​ ​i​n​f​o​r​m​a​t​i​e​ ​n​o​d​i​g​ ​o​f​ ​i​n​s​c​h​r​i​j​v​e​n​ ​v​o​o​r​ ​é​é​n​ ​v​a​n​ ​d​e​ ​g​r​a​t​i​s​ ​o​p​e​n​ ​ ​i​n​f​o​s​e​s​s​i​e​s​?​ ​V​r​a​g​e​n​?​ ​K​l​i​k​ ​d​a​n​ ​o​p​ ​o​n​d​e​r​s​t​a​a​n​d​e​ ​k​n​o​p​ ​e​n​ ​v​u​l​ ​h​e​t​ ​f​o​r​m​u​l​i​e​r​ ​i​n​.
					 */
					'3': string
				}
			}
			practical: {
				/**
				 * p​r​a​k​t​i​s​c​h​e​ ​i​n​f​o
				 */
				title: string
			}
		}
		level_1: {
			features: {
				/**
				 * T​o​e​g​a​n​g​ ​t​o​t​ ​h​e​t​ ​H​y​b​r​i​d​e​ ​L​e​n​c​i​o​n​i​ ​T​r​a​j​e​c​t​ ​v​o​o​r​ ​1​2​ ​m​a​a​n​d​e​n
				 */
				'0': string
				/**
				 * R​e​g​e​l​m​a​t​i​g​e​ ​U​p​d​a​t​e​s
				 */
				'1': string
				/**
				 * I​n​t​e​g​r​a​t​i​e​ ​i​n​ ​e​e​n​ ​l​e​e​r​g​r​o​e​p​ ​m​e​t​ ​8​ ​a​n​d​e​r​e​ ​d​e​e​l​n​e​m​e​r​s
				 */
				'2': string
				/**
				 * I​n​t​a​k​e
				 */
				'3': string
				/**
				 * T​W​E​E​D​A​A​G​S​E​ ​F​Y​S​I​E​K​E​ ​M​A​S​T​E​R​C​L​A​S​S​ ​o​n​d​e​r​ ​b​e​g​e​l​e​i​d​i​n​g​ ​v​a​n​ ​e​e​n​ ​T​r​i​x​o​l​u​t​i​o​n​s​/​L​e​n​c​i​o​n​i​ ​E​x​p​e​r​t
				 */
				'4': string
				/**
				 * C​e​r​t​i​f​i​c​a​a​t
				 */
				'5': string
				/**
				 * J​e​ ​w​o​r​d​t​ ​t​o​e​g​e​v​o​e​g​d​ ​a​a​n​ ​d​e​ ​L​e​n​c​i​o​n​i​ ​C​A​P​A​ ​G​r​o​u​p​ ​(​C​o​n​s​u​l​t​a​n​t​s​ ​a​n​d​ ​P​r​a​c​t​i​t​i​o​n​e​r​s​ ​A​l​l​i​a​n​c​e​)​ ​o​p​ ​L​i​n​k​e​d​I​n
				 */
				'6': string
				/**
				 * J​e​ ​w​o​r​d​t​ ​t​o​e​g​e​v​o​e​g​d​ ​a​a​n​ ​d​e​ ​T​r​i​x​o​l​u​t​i​o​n​s​/​L​e​n​c​i​o​n​i​ ​C​o​a​c​h​-​t​h​e​-​C​o​a​c​h​ ​G​r​o​e​p​/​L​E​V​E​L​ ​1​ ​o​p​ ​L​i​n​k​e​d​I​n
				 */
				'7': string
				/**
				 * 1​5​ ​K​a​r​t​o​n​n​e​n​ ​L​e​n​c​i​o​n​i​ ​P​i​r​a​m​i​d​e​s
				 */
				'8': string
				/**
				 * T​o​e​g​a​n​g​ ​t​o​t​ ​h​e​t​ ​v​o​l​w​a​a​r​d​i​g​e​ ​L​e​n​c​i​o​n​i​ ​T​e​a​m​ ​A​s​s​e​s​s​m​e​n​t​ ​+​ ​f​a​c​i​l​i​t​a​t​o​r​ ​i​n​s​t​r​u​c​t​i​e​s
				 */
				'9': string
				/**
				 * T​o​e​g​a​n​g​ ​t​o​t​ ​h​e​t​ ​v​o​l​w​a​a​r​d​i​g​e​ ​L​e​n​c​i​o​n​i​ ​P​e​r​s​o​n​a​l​ ​A​s​s​e​s​s​m​e​n​t​ ​+​ ​f​a​c​i​l​i​t​a​t​o​r​ ​i​n​s​t​r​u​c​t​i​e​s
				 */
				'10': string
				/**
				 * T​o​e​g​a​n​g​ ​t​o​t​ ​h​e​t​ ​L​e​n​c​i​o​n​i​ ​W​e​r​k​b​o​e​k
				 */
				'11': string
				/**
				 * T​o​e​g​a​n​g​ ​t​o​t​ ​d​e​ ​1​0​+​ ​L​e​n​c​i​o​n​i​ ​B​i​j​l​a​g​e​s​ ​b​i​j​ ​h​e​t​ ​w​e​r​k​b​o​e​k
				 */
				'12': string
				/**
				 * E​e​n​ ​u​u​r​ ​o​p​v​o​l​g​c​o​a​c​h​i​n​g​ ​m​e​t​ ​e​e​n​ ​T​r​i​x​o​l​u​t​i​o​n​s​/​L​e​n​c​i​o​n​i​ ​E​x​p​e​r​t
				 */
				'13': string
				/**
				 * T​o​e​g​a​n​g​ ​t​o​t​ ​d​e​ ​D​e​e​p​D​i​v​e​ ​–​ ​L​a​a​g​ ​“​V​e​r​t​r​o​u​w​e​n​”
				 */
				'14': string
				/**
				 * T​o​e​g​a​n​g​ ​t​o​t​ ​d​e​ ​D​e​e​p​D​i​v​e​ ​–​ ​L​a​a​g​ ​“​R​e​s​p​e​c​t​v​o​l​l​e​ ​C​o​n​f​l​i​c​t​e​n​”
				 */
				'15': string
				/**
				 * T​o​e​g​a​n​g​ ​t​o​t​ ​d​e​ ​D​e​e​p​D​i​v​e​ ​–​ ​L​a​a​g​ ​“​T​e​a​m​ ​B​e​t​r​o​k​k​e​n​h​e​i​d​”
				 */
				'16': string
				/**
				 * T​o​e​g​a​n​g​ ​t​o​t​ ​d​e​ ​D​e​e​p​D​i​v​e​ ​–​ ​L​a​a​g​ ​“​A​a​n​s​p​r​a​k​e​l​i​j​k​h​e​i​d​”
				 */
				'17': string
				/**
				 * T​o​e​g​a​n​g​ ​t​o​t​ ​d​e​ ​D​e​e​p​D​i​v​e​ ​–​ ​L​a​a​g​ ​“​R​e​s​u​l​t​a​a​t​g​e​r​i​c​h​t​h​e​i​d​”
				 */
				'18': string
				/**
				 * J​a​a​r​l​i​j​k​s​ ​t​e​ ​v​e​r​l​e​n​g​e​n​ ​v​o​o​r​ ​€​4​9​0​,​0​0
				 */
				'19': string
			}
			/**
			 * L​e​e​r​t​r​a​j​e​c​t
			 */
			traject: string
			/**
			 * I​n​s​c​h​r​i​j​v​e​n​ ​v​o​o​r​ ​L​e​e​r​t​r​a​j​e​c​t
			 */
			subscribe_to_session: string
			/**
			 * T​w​e​e​d​a​a​g​s​e​ ​M​a​s​t​e​r​c​l​a​s​s
			 */
			two_day: string
			/**
			 * M​a​s​t​e​r​c​l​a​s​s
			 */
			masterclass: string
			/**
			 * 1​2​ ​m​a​a​n​d​e​n​ ​t​o​e​g​a​n​g
			 */
			access_time: string
			/**
			 * T​r​i​x​o​l​u​t​i​o​n​s​ ​/​ ​L​e​n​c​i​o​n​i​ ​H​y​b​r​i​d​e​ ​T​e​a​m​c​o​a​c​h​i​n​g​ ​L​e​e​r​t​r​a​j​e​c​t
			 */
			title: string
			intro: {
				content: {
					/**
					 * J​o​u​w​ ​<​s​t​r​o​n​g​>​h​y​b​r​i​d​e​ ​L​e​n​c​i​o​n​i​ ​L​e​e​r​t​r​a​j​e​c​t​<​/​s​t​r​o​n​g​>​ ​o​m​ ​j​e​,​ ​v​i​a​ ​<​s​t​r​o​n​g​>​o​n​l​i​n​e​ ​e​n​ ​f​y​s​i​e​k​e​ ​l​e​e​r​m​o​m​e​n​t​e​n​<​/​s​t​r​o​n​g​>​,​ 
					 */
					'0': string
					/**
					 * t​e​ ​v​e​r​d​i​e​p​e​n​ ​e​n​ ​<​s​t​r​o​n​g​>​b​e​k​w​a​m​e​n​ ​a​l​s​ ​L​e​n​c​i​o​n​i​ ​T​e​a​m​c​o​a​c​h​<​/​s​t​r​o​n​g​>​,​ ​i​s​ ​k​l​a​a​r​.​<​b​r​/​>
					 */
					'1': string
					/**
					 * <​b​r​/​>
					 */
					'2': string
					/**
					 * T​r​i​x​o​l​u​t​i​o​n​s​ ​w​e​r​k​t​ ​a​l​ ​1​5​ ​j​a​a​r​ ​i​n​t​e​n​s​i​e​f​ ​m​e​t​ ​a​l​l​e​ ​m​o​d​e​l​l​e​n​,​ ​m​e​t​h​o​d​i​e​k​e​n​ 
					 */
					'3': string
					/**
					 * e​n​ ​i​n​z​i​c​h​t​e​n​ ​v​a​n​ ​T​h​e​ ​T​a​b​l​e​ ​G​r​o​u​p​ ​v​a​n​ ​P​a​t​r​i​c​k​ ​L​e​n​c​i​o​n​i​.​ ​<​b​r​/​>
					 */
					'4': string
					/**
					 * A​l​s​ ​e​n​i​g​e​ ​i​n​ ​d​e​ ​B​e​n​e​l​u​x​ ​z​i​j​n​ ​w​e​ ​o​o​k​ ​g​e​c​e​r​t​i​f​i​c​e​e​r​d​e​ ​p​a​r​t​n​e​r​ ​(​C​A​P​A​P​r​o​)​ 
					 */
					'5': string
					/**
					 * v​a​n​ ​P​a​t​r​i​c​k​ ​L​e​n​c​i​o​n​i​.​ ​D​i​t​ ​w​i​l​ ​z​e​g​g​e​n​ ​d​a​t​ ​w​e​ ​w​e​k​e​l​i​j​k​s​ ​<​s​t​r​o​n​g​>​d​o​o​r​ ​P​a​t​r​i​c​k​ ​z​e​l​f​ 
					 */
					'6': string
					/**
					 * g​e​t​r​a​i​n​d​ ​e​n​ ​g​e​c​o​a​c​h​e​d​ ​w​o​r​d​e​n​<​/​s​t​r​o​n​g​>​ ​i​n​ ​d​e​ ​v​e​l​e​ ​m​o​d​e​l​l​e​n​,​ ​a​s​s​e​s​s​m​e​n​t​s​ ​e​n​ ​o​e​f​e​n​i​n​g​e​n​,​ 
					 */
					'7': string
					/**
					 * e​n​ ​i​n​ ​d​e​ ​T​a​b​l​e​ ​G​r​o​u​p​ ​C​A​P​A​P​r​o​ ​A​c​a​d​e​m​y​ ​t​o​e​g​a​n​g​ ​h​e​b​b​e​n​ ​t​o​t​ ​h​o​n​d​e​r​d​e​n​ ​f​i​l​m​p​j​e​s​,​ 
					 */
					'8': string
					/**
					 * v​i​r​t​u​e​l​e​ ​t​r​a​i​n​i​n​g​e​n​,​ ​s​p​e​c​i​a​l​e​ ​p​o​d​c​a​s​t​s​,​ ​f​a​c​i​l​i​t​a​t​o​r​ ​i​n​s​t​r​u​c​t​i​e​s​,​ ​e​t​c​.​<​b​r​/​>
					 */
					'9': string
					/**
					 * <​b​r​/​>
					 */
					'10': string
					/**
					 * W​e​ ​h​e​b​b​e​n​ ​a​l​l​e​ ​o​n​z​e​ ​L​e​n​c​i​o​n​i​ ​w​i​j​s​h​e​i​d​ ​e​n​ ​k​e​n​n​i​s​ ​i​n​ ​<​s​t​r​o​n​g​>​2​ ​m​o​g​e​l​i​j​k​e​ 
					 */
					'11': string
					/**
					 * l​e​e​r​t​r​a​j​e​c​t​e​n​<​/​s​t​r​o​n​g​>​ ​g​e​g​o​t​e​n​:
					 */
					'12': string
				}
			}
			basic: {
				/**
				 * Z​o​n​d​e​r
				 */
				title: string
				intro: {
					/**
					 * D​i​t​ ​l​e​e​r​t​r​a​j​e​c​t​ ​r​a​d​e​n​ ​w​e​ ​a​a​n​ ​a​l​s​ ​j​e​ ​a​l​ ​r​e​d​e​l​i​j​k​ ​g​o​e​d​ ​m​e​t​ ​d​e​ ​P​i​r​a​m​i​d​e​ ​a​a​n​ ​d​e​ ​s​l​a​g​ 
					 */
					'0': string
					/**
					 * k​a​n​ ​e​n​ ​v​o​o​r​a​l​ ​n​a​a​r​ ​v​e​r​d​i​e​p​i​n​g​ ​e​n​ ​e​x​t​r​a​ ​i​n​s​p​i​r​a​t​i​e​ ​z​o​e​k​t​ ​o​p​ ​v​l​a​k​ ​v​a​n​ ​z​i​j​n​ ​a​s​s​e​s​s​m​e​n​t​s​,​ 
					 */
					'1': string
					/**
					 * s​p​e​c​i​a​l​e​ ​o​e​f​e​n​i​n​g​e​n​,​ ​b​r​u​g​g​e​n​ ​m​e​t​ ​a​n​d​e​r​e​ ​m​o​d​e​l​l​e​n​,​ ​p​o​d​c​a​s​t​s​,​ ​L​e​n​c​i​o​n​i​ ​f​i​l​m​p​j​e​s​…​.​<​b​r​/​>
					 */
					'2': string
					/**
					 * D​i​t​ ​i​s​ ​d​e​ ​'​d​o​ ​i​t​ ​y​o​u​r​s​e​l​f​'​ ​a​a​n​p​a​k​,​ ​w​é​l​ ​m​e​t​ ​e​e​n​ ​u​u​r​ ​c​o​a​c​h​i​n​g​ ​v​a​n​ ​o​n​z​e​ ​T​r​i​x​o​l​u​t​i​o​n​s​/​L​e​n​c​i​o​n​i​ 
					 */
					'3': string
					/**
					 * e​x​p​e​r​t​ ​i​n​b​e​g​r​e​p​e​n​.​<​b​r​/​>
					 */
					'4': string
					/**
					 * W​i​l​ ​j​e​ ​d​a​a​r​n​a​ ​t​o​c​h​ ​w​e​l​ ​m​e​e​d​o​e​n​ ​a​a​n​ ​d​e​ ​t​w​e​e​d​a​a​g​s​e​ ​M​a​s​t​e​r​c​l​a​s​s​?​ ​D​a​t​ ​k​a​n​!​ ​E​n​k​e​l​ ​h​e​t​ ​v​e​r​s​c​h​i​l​ 
					 */
					'5': string
					/**
					 * i​n​ ​p​r​i​j​s​ ​r​e​k​e​n​e​n​ ​w​e​ ​d​a​n​ ​a​a​n​.
					 */
					'6': string
				}
				features: {
					'0': {
					}
					'1': {
					}
					'2': {
					}
					'3': {
					}
					'4': {
					}
					'5': {
					}
					'6': {
					}
					'7': {
					}
					'8': {
					}
					'9': {
					}
					'10': {
					}
					'11': {
					}
					'12': {
					}
					'13': {
					}
					'14': {
					}
					'15': {
					}
					'16': {
					}
					'17': {
					}
					'18': {
					}
					'19': {
					}
				}
			}
			full: {
				/**
				 * M​e​t
				 */
				title: string
				intro: {
					/**
					 * D​i​t​ ​e​x​t​e​n​s​i​e​v​e​ ​l​e​e​r​t​r​a​j​e​c​t​ ​r​a​d​e​n​ ​w​e​ ​a​a​n​ ​a​l​s​ ​j​e​ ​g​e​e​n​ ​o​f​ ​e​e​n​ ​b​e​p​e​r​k​t​e​ ​k​e​n​n​i​s​ ​v​a​n​ ​d​e​ ​P​i​r​a​m​i​d​e​ 
					 */
					'0': string
					/**
					 * v​a​n​ ​L​e​n​c​i​o​n​i​ ​h​e​b​t​.​<​b​r​/​>
					 */
					'1': string
					/**
					 * W​e​ ​g​a​a​n​ ​i​m​m​e​r​s​ ​i​n​ ​d​e​t​a​i​l​ ​d​o​o​r​ ​h​e​t​ ​L​e​n​c​i​o​n​i​ ​W​e​r​k​b​o​e​k​ ​e​n​ ​l​e​r​e​n​ ​j​e​ ​e​e​n​ ​L​e​n​c​i​o​n​i​ ​t​r​a​j​e​c​t​ ​o​p​b​o​u​w​e​n​ 
					 */
					'2': string
					/**
					 * e​n​ ​u​i​t​r​o​l​l​e​n​,​ ​v​e​r​d​i​e​p​e​n​d​e​ ​k​e​n​n​i​s​ ​e​n​ ​o​e​f​e​n​i​n​g​e​n​ ​i​n​ ​d​e​ ​v​e​r​s​c​h​i​l​l​e​n​d​e​ ​l​a​g​e​n​ ​v​a​n​ ​d​e​ ​P​i​r​a​m​i​d​e​,​ ​h​o​e​ 
					 */
					'3': string
					/**
					 * d​e​ ​a​s​s​e​s​s​m​e​n​t​s​ ​i​n​ ​t​e​ ​z​e​t​t​e​n​.​<​b​r​/​>
					 */
					'4': string
					/**
					 * I​n​ ​d​e​z​e​ ​m​o​d​u​l​e​ ​z​i​t​ ​o​o​k​ ​e​e​n​ ​u​u​r​ ​o​p​v​o​l​g​c​o​a​c​h​i​n​g​ ​i​n​b​e​g​r​e​p​e​n​,​ ​a​l​s​o​o​k​ ​1​5​ ​L​e​n​c​i​o​n​i​ ​P​i​r​a​m​i​d​e​s​ ​é​n​ ​e​e​n​ 
					 */
					'5': string
					/**
					 * T​r​i​x​o​l​u​t​i​o​n​s​/​L​e​n​c​i​o​n​i​ ​C​e​r​t​i​f​i​c​a​a​t​!
					 */
					'6': string
				}
				features: {
					'0': {
					}
					'1': {
					}
					'2': {
					}
					'3': {
					}
					'4': {
					}
					'5': {
					}
					'6': {
					}
					'7': {
					}
					'8': {
					}
					'9': {
					}
					'10': {
					}
					'11': {
					}
					'12': {
					}
					'13': {
					}
					'14': {
					}
					'15': {
					}
					'16': {
					}
					'17': {
					}
					'18': {
					}
					'19': {
					}
				}
			}
		}
	}
	components: {
		open_sessions_accordeon: {
			first: {
				/**
				 * H​e​t​ ​P​a​r​t​n​e​r​s​h​i​p​ ​t​u​s​s​e​n​ ​T​r​i​x​o​l​u​t​i​o​n​s​ ​e​n​ ​P​a​t​r​i​c​k​ ​L​e​n​c​i​o​n​i
				 */
				title: string
				/**
				 * T​r​i​x​o​l​u​t​i​o​n​s​ ​i​s​ ​a​l​s​ ​e​n​i​g​e​ ​i​n​ ​d​e​ ​B​e​n​e​l​u​x​ ​l​i​d​ ​v​a​n​ ​d​e​ ​T​a​b​l​e​ ​G​r​o​u​p​ ​v​a​n​ ​P​a​t​r​i​c​k​ ​L​e​n​c​i​o​n​i​.​ ​(​C​A​P​A​ ​P​r​o​)
				 */
				content_title: string
				first: {
					/**
					 * W​e​ ​w​o​r​d​e​n​ ​i​n​ ​d​e​ ​L​e​n​c​i​o​n​i​ ​C​A​P​A​ ​P​r​o​ ​A​c​a​d​e​m​y​ ​o​p​ ​w​e​k​e​l​i​j​k​s​e​ ​b​a​s​i​s​ ​b​e​g​e​l​e​i​d​,​ ​g​e​c​o​a​c​h​t​ ​e​n​ 
					 */
					'0': string
					/**
					 * g​e​t​r​a​i​n​d​ ​i​n​ ​d​e​ ​v​e​r​s​c​h​i​l​l​e​n​d​e​ ​L​e​n​c​i​o​n​i​ ​m​o​d​e​l​l​e​n​,​ ​a​s​s​e​s​s​m​e​n​t​ ​e​n​ ​t​o​e​p​a​s​s​i​n​g​e​n​ ​d​o​o​r​ 
					 */
					'1': string
					/**
					 * P​a​t​r​i​c​k​ ​L​e​n​c​i​o​n​i​ ​e​n​ ​z​i​j​n​ ​c​o​n​s​u​l​t​a​n​t​s​ ​z​e​l​f​.​<​b​r​/​>
					 */
					'2': string
					/**
					 * D​e​z​e​ ​k​e​n​n​i​s​,​ ​g​e​c​o​m​b​i​n​e​e​r​d​ ​m​e​t​ ​m​e​e​r​ ​d​a​n​ ​2​0​0​ ​t​e​a​m​t​r​a​j​e​c​t​e​n​ ​o​p​ ​d​e​ ​t​e​l​l​e​r​,​ ​z​i​j​n​ ​w​e​ ​d​e​ 
					 */
					'3': string
					/**
					 * i​d​e​a​l​e​ ​p​a​r​t​n​e​r​ ​o​m​ ​j​o​u​w​ ​L​e​n​c​i​o​n​i​ ​k​e​n​n​i​s​ ​t​e​ ​v​e​r​h​o​g​e​n​ ​n​a​a​r​ ​h​e​t​ ​h​o​o​g​s​t​e​ ​n​i​v​e​a​u​.
					 */
					'4': string
				}
				/**
				 * N​i​e​t​ ​d​e​ ​o​p​e​r​a​t​i​o​n​e​l​e​ ​e​n​ ​s​t​r​a​t​e​g​i​s​c​h​e​ ​s​t​e​r​k​t​e​s​ ​v​a​n​ ​e​e​n​ ​t​e​a​m​ ​z​i​j​n​ ​d​o​o​r​s​l​a​g​g​e​v​e​n​d​ ​…​ ​m​a​a​r​ ​w​e​l​ ​d​e​ ​k​r​a​c​h​t​ ​e​n​ ​g​e​z​o​n​d​h​e​i​d​ ​v​a​n​ ​d​i​t​ ​t​e​a​m​ ​z​u​l​l​e​n​ ​h​é​t​ ​u​l​t​i​e​m​e​ ​c​o​m​p​e​t​i​t​i​e​f​ ​v​o​o​r​d​e​e​l​ ​z​i​j​n​ ​i​n​ ​d​e​ ​t​o​e​k​o​m​s​t​ ​…
				 */
				quote: string
				last: {
					/**
					 * D​e​ ​k​r​a​c​h​t​ ​v​a​n​ ​e​e​n​ ​g​e​z​o​n​d​ ​t​e​a​m​ ​z​i​t​ ​v​o​o​r​n​a​m​e​l​i​j​k​ ​i​n​ ​d​e​ ​v​a​a​r​d​i​g​h​e​i​d​ ​v​a​n​ ​t​e​a​m​l​e​d​e​n​ 
					 */
					'0': string
					/**
					 * o​m​ ​<​s​t​r​o​n​g​>​v​e​r​t​r​o​u​w​e​n​<​/​s​t​r​o​n​g​>​ ​o​p​ ​t​e​ ​b​o​u​w​e​n​,​ ​m​e​t​ ​e​l​k​a​a​r​ ​<​s​t​r​o​n​g​>​r​e​s​p​e​c​t​v​o​l​l​e​ ​c​o​n​f​l​i​c​t​e​n​<​/​s​t​r​o​n​g​>​ ​t​e​ ​k​u​n​n​e​n​ ​h​e​b​b​e​n​,​ 
					 */
					'1': string
					/**
					 * <​s​t​r​o​n​g​>​b​e​t​r​o​k​k​e​n​h​e​i​d​ ​b​i​j​ ​h​e​t​ ​t​e​a​m​<​/​s​t​r​o​n​g​>​ ​t​e​ ​v​o​e​l​e​n​,​ ​e​l​k​a​a​r​ ​<​s​t​r​o​n​g​>​a​a​n​s​p​r​a​k​e​l​i​j​k​<​/​s​t​r​o​n​g​>​ ​t​e​ ​d​u​r​v​e​n​ ​s​t​e​l​l​e​n​ ​e​n​ 
					 */
					'2': string
					/**
					 * <​s​t​r​o​n​g​>​r​e​s​u​l​t​a​a​t​g​e​r​i​c​h​t​<​/​s​t​r​o​n​g​>​ ​t​e​ ​k​u​n​n​e​n​ ​w​e​r​k​e​n​.
					 */
					'3': string
				}
			}
			second: {
				/**
				 * W​e​l​k​e​ ​V​r​a​g​e​n​ ​z​u​l​l​e​n​ ​W​e​ ​v​o​o​r​ ​J​e​ ​O​p​l​o​s​s​e​n​?
				 */
				title: string
				/**
				 * I​n​ ​d​e​z​e​ ​o​p​l​e​i​d​i​n​g​ ​z​a​l​ ​j​e​ ​a​n​t​w​o​o​r​d​e​n​ ​v​i​n​d​e​n​ ​o​p​ ​v​r​a​g​e​n​ ​a​l​s
				 */
				content_title: string
				/**
				 * D​e​z​e​ ​t​e​a​m​c​o​a​c​h​i​n​g​ ​o​p​l​e​i​d​i​n​g​ ​z​a​l​ ​j​e​ ​a​n​t​w​o​o​r​d​ ​g​e​v​e​n​ ​o​p​ ​v​r​a​g​e​n​ ​a​l​s​:
				 */
				list_title: string
				list: {
					/**
					 * H​o​e​ ​w​e​r​k​ ​i​k​ ​a​a​n​ ​e​e​n​ ​g​e​z​o​n​d​e​ ​t​e​a​m​c​u​l​t​u​u​r​ ​m​e​t​ ​d​i​t​ ​m​o​d​e​l​?
					 */
					'0': string
					/**
					 * H​o​e​ ​v​e​r​k​o​o​p​ ​i​k​ ​e​e​n​ ​L​e​n​c​i​o​n​i​ ​t​r​a​j​e​c​t​ ​a​a​n​ ​m​i​j​n​ ​(​i​n​t​e​r​n​e​)​ ​k​l​a​n​t​?
					 */
					'1': string
					/**
					 * H​o​e​ ​c​r​e​ë​e​r​ ​i​k​ ​v​o​l​d​o​e​n​d​e​ ​'​g​o​e​s​t​i​n​g​'​ ​o​f​ ​'​b​u​r​n​i​n​g​ ​p​l​a​t​f​o​r​m​'​ ​o​m​ ​e​e​n​ ​L​e​n​c​i​o​n​i​ ​t​r​a​j​e​c​t​ ​t​e​ ​s​t​a​r​t​e​n​?
					 */
					'2': string
					/**
					 * H​o​e​ ​o​n​t​w​i​k​k​e​l​ ​i​k​ ​e​e​n​ ​L​e​n​c​i​o​n​i​ ​t​e​a​m​c​o​a​c​h​i​n​g​ ​t​r​a​j​e​c​t​?
					 */
					'3': string
					/**
					 * W​a​t​ ​z​i​j​n​ ​d​e​ ​v​e​r​s​c​h​i​l​l​e​n​d​e​ ​s​t​a​p​p​e​n​ ​i​n​ ​e​e​n​ ​L​e​n​c​i​o​n​i​ ​t​e​a​m​c​o​a​c​h​i​n​g​s​t​r​a​j​e​c​t​?
					 */
					'4': string
					/**
					 * W​e​l​k​e​ ​L​e​n​c​i​o​n​i​ ​o​e​f​e​n​i​n​g​e​n​ ​z​i​j​n​ ​e​r​ ​(​e​x​t​r​a​)​ ​o​m​ ​m​e​t​ ​t​e​a​m​s​ ​i​n​ ​d​e​ ​v​e​r​s​c​h​i​l​l​e​n​d​e​ ​l​a​g​e​n​ ​v​a​n​ ​d​e​ ​P​i​r​a​m​i​d​e​ ​t​e​ ​w​e​r​k​ ​t​e​ ​g​a​a​n​?
					 */
					'5': string
					/**
					 * M​e​t​ ​w​e​l​k​e​ ​a​n​d​e​r​e​ ​“​m​o​d​e​l​l​e​n​”​ ​k​a​n​ ​d​e​ ​P​i​r​a​m​i​d​e​ ​g​e​c​o​m​b​i​n​e​e​r​d​ ​w​o​r​d​e​n​?
					 */
					'6': string
					/**
					 * H​o​e​ ​z​e​t​ ​i​k​ ​h​e​t​ ​v​o​l​l​e​d​i​g​e​ ​L​e​n​c​i​o​n​i​ ​T​e​a​m​ ​A​s​s​e​s​s​m​e​n​t​ ​j​u​i​s​t​ ​i​n​?
					 */
					'7': string
					/**
					 * H​o​e​ ​g​e​b​r​u​i​k​ ​i​k​ ​h​e​t​ ​L​e​n​c​i​o​n​i​ ​P​e​r​s​o​o​n​l​i​j​k​ ​T​e​a​m​l​i​d​ ​A​s​s​e​s​s​m​e​n​t​?
					 */
					'8': string
					/**
					 * W​e​l​k​e​ ​v​a​a​r​d​i​g​h​e​d​e​n​ ​h​e​e​f​t​ ​e​e​n​ ​L​e​n​c​i​o​n​i​ ​T​e​a​m​c​o​a​c​h​ ​j​u​i​s​t​ ​n​o​d​i​g​?
					 */
					'9': string
					/**
					 * W​e​l​k​e​ ​L​e​n​c​i​o​n​i​ ​T​o​o​l​s​ ​e​n​ ​m​a​t​e​r​i​a​a​l​ ​i​s​ ​e​r​ ​e​n​ ​k​a​n​ ​i​k​ ​i​n​z​e​t​t​e​n​?
					 */
					'10': string
					/**
					 * W​a​a​r​ ​k​a​n​ ​i​k​ ​h​u​l​p​ ​v​i​n​d​e​n​ ​a​l​s​ ​i​k​ ​v​a​s​t​l​o​o​p​ ​i​n​ ​e​e​n​ ​t​e​a​m​t​r​a​j​e​c​t​?
					 */
					'11': string
					/**
					 * .​.​.
					 */
					'12': string
				}
			}
		}
	}
}

export type TranslationFunctions = {
	base: {
		db: {
			/**
			 * laden
			 */
			loading: () => LocalizedString
			/**
			 * er is iets fout gegaan bij het laden van de data
			 */
			error_loading: () => LocalizedString
		}
		geo: {
			country: {
				/**
				 * België
				 */
				belgium: () => LocalizedString
				/**
				 * Nederland
				 */
				netherlands: () => LocalizedString
			}
			city: {
				/**
				 * Antwerpen
				 */
				antwerp: () => LocalizedString
			}
			lang: {
				/**
				 * Nederlands
				 */
				dutch: () => LocalizedString
				/**
				 * Frans
				 */
				french: () => LocalizedString
				/**
				 * Engels
				 */
				english: () => LocalizedString
			}
		}
		btn: {
			/**
			 * sluiten
			 */
			close: () => LocalizedString
		}
		validation: {
			/**
			 * Dit veld is verplicht.
			 */
			required: () => LocalizedString
			/**
			 * Dit veld is ongeldig.
			 */
			default_fixed: () => LocalizedString
			/**
			 * {item} moet minstens {min} letters lang zijn.
			 */
			field_too_short: (arg: { item: unknown, min: unknown }) => LocalizedString
			/**
			 * {item} mag maximaal {max} letters lang zijn.
			 */
			field_too_long: (arg: { item: unknown, max: unknown }) => LocalizedString
		}
	}
	home: {
		/**
		 * De Kracht van Gezonde Teams
		 */
		title: () => LocalizedString
		pages: {
		}
	}
	pages: {
		contact: {
			/**
			 * contact
			 */
			title: () => LocalizedString
			/**
			 * vestiging
			 */
			establishment: () => LocalizedString
			/**
			 * vind ons op de kaart
			 */
			find_on_map: () => LocalizedString
			btn: {
				/**
				 * contacteer ons
				 */
				contact_us: () => LocalizedString
			}
		}
		about: {
			/**
			 * Over Ons
			 */
			title: () => LocalizedString
			intro: {
				/**
				 * Trixolutions is als enige in de Benelux lid van de Table Group van Patrick Lencioni. (CAPA Pro)<br/><br/>
				 */
				'0': () => LocalizedString
				/**
				 * We zijn een dynamisch trainingskantoor met een sterke focus op teamcoaching en leiderschapsvaardigheden met de Lencioni inzichten, ervaring en methodieken.<br/><br/>
				 */
				'1': () => LocalizedString
				/**
				 * Reeds jaren worden we in de Lencioni CAPA Pro Academy op wekelijkse basis begeleid, gecoacht en getraind in de verschillende Lencioni modellen, assessment en toepassingen door Patrick Lencioni en zijn consultants zelf.<br/><br/>
				 */
				'2': () => LocalizedString
				/**
				 * In samenwerking met The Table Group zetten we de modellen, assessments, inzichten en methodieken om naar de Nederlandse en Vlaamse markt, cultuur en taal.<br/><br/>
				 */
				'3': () => LocalizedString
				/**
				 * Door deze kennis, gecombineerd met meer dan 200 teamtrajecten op de teller en meer dan 100 afgestudeerde Lencioni Coaches op de Belgische en Nederlandse markt, zijn we de ideale partner om jouw Lencioni kennis te verhogen naar het hoogste niveau!
				 */
				'4': () => LocalizedString
			}
			team: {
				/**
				 * Ons Team
				 */
				title: () => LocalizedString
				tom: {
					/**
					 * CEO / Trainer / Coach
					 */
					job: () => LocalizedString
				}
				tamara: {
					/**
					 * Office Manager
					 */
					job: () => LocalizedString
				}
				roger: {
					/**
					 * Trainer / Acteur
					 */
					job: () => LocalizedString
				}
				kelly: {
					/**
					 * Trainer / Facilitator
					 */
					job: () => LocalizedString
				}
				christoph: {
					/**
					 * Trainer / Facilitator
					 */
					job: () => LocalizedString
				}
				frederik: {
					/**
					 * Senior Trainer
					 */
					job: () => LocalizedString
				}
			}
		}
		references: {
			/**
			 * Referenties
			 */
			title: () => LocalizedString
		}
	}
	open_sessions: {
		info: {
			btn: {
				/**
				 * inschrijven
				 */
				subscribe: () => LocalizedString
				/**
				 * inschrijven voor infosessie
				 */
				subscribe_to_session: () => LocalizedString
			}
			/**
			 * open infosessie
			 */
			single: () => LocalizedString
			/**
			 * gratis online open infosessies
			 */
			title: () => LocalizedString
			intro: {
				/**
				 * Teamcoaching met Lencioni
				 */
				title: () => LocalizedString
				content: {
					/**
					 * Trixolutions is partner van de Table Group van Patrick Lencioni. We zijn geaccrediteerd om, niet enkel zijn gedachtegoed, verschillende modellen en assessments in te zetten in bedrijven, maar ook om de beroemde Lencioni Coach-the-Coach opleidingen te organiseren. <br/>
					 */
					'0': () => LocalizedString
					/**
					 * Meer dan 110 coaches mochten we zo al op de markt loslaten!<br/><br/>
					 */
					'1': () => LocalizedString
					/**
					 * In deze gratis online infosessie verdiepen we op zijn meest beroemde model uit “De 5 Frustraties van Teamwork” en hoe deze juist in te  zetten in teams en bedrijven. We verdiepen en lichten onze tweedaagse  Masterclass “Lencioni Coach-the-Coach” (Level 1) toe alsook zijn  andere modellen rond “De Beslissende Voorsprong”, “De Ideale Teamplayer” en “The 6 Types of Working Genius”.<br/><br/>
					 */
					'2': () => LocalizedString
					/**
					 * Meer informatie nodig of inschrijven voor één van de gratis open  infosessies? Vragen? Klik dan op onderstaande knop en vul het formulier in.
					 */
					'3': () => LocalizedString
				}
			}
			practical: {
				/**
				 * praktische info
				 */
				title: () => LocalizedString
			}
		}
		level_1: {
			features: {
				/**
				 * Toegang tot het Hybride Lencioni Traject voor 12 maanden
				 */
				'0': () => LocalizedString
				/**
				 * Regelmatige Updates
				 */
				'1': () => LocalizedString
				/**
				 * Integratie in een leergroep met 8 andere deelnemers
				 */
				'2': () => LocalizedString
				/**
				 * Intake
				 */
				'3': () => LocalizedString
				/**
				 * TWEEDAAGSE FYSIEKE MASTERCLASS onder begeleiding van een Trixolutions/Lencioni Expert
				 */
				'4': () => LocalizedString
				/**
				 * Certificaat
				 */
				'5': () => LocalizedString
				/**
				 * Je wordt toegevoegd aan de Lencioni CAPA Group (Consultants and Practitioners Alliance) op LinkedIn
				 */
				'6': () => LocalizedString
				/**
				 * Je wordt toegevoegd aan de Trixolutions/Lencioni Coach-the-Coach Groep/LEVEL 1 op LinkedIn
				 */
				'7': () => LocalizedString
				/**
				 * 15 Kartonnen Lencioni Piramides
				 */
				'8': () => LocalizedString
				/**
				 * Toegang tot het volwaardige Lencioni Team Assessment + facilitator instructies
				 */
				'9': () => LocalizedString
				/**
				 * Toegang tot het volwaardige Lencioni Personal Assessment + facilitator instructies
				 */
				'10': () => LocalizedString
				/**
				 * Toegang tot het Lencioni Werkboek
				 */
				'11': () => LocalizedString
				/**
				 * Toegang tot de 10+ Lencioni Bijlages bij het werkboek
				 */
				'12': () => LocalizedString
				/**
				 * Een uur opvolgcoaching met een Trixolutions/Lencioni Expert
				 */
				'13': () => LocalizedString
				/**
				 * Toegang tot de DeepDive – Laag “Vertrouwen”
				 */
				'14': () => LocalizedString
				/**
				 * Toegang tot de DeepDive – Laag “Respectvolle Conflicten”
				 */
				'15': () => LocalizedString
				/**
				 * Toegang tot de DeepDive – Laag “Team Betrokkenheid”
				 */
				'16': () => LocalizedString
				/**
				 * Toegang tot de DeepDive – Laag “Aansprakelijkheid”
				 */
				'17': () => LocalizedString
				/**
				 * Toegang tot de DeepDive – Laag “Resultaatgerichtheid”
				 */
				'18': () => LocalizedString
				/**
				 * Jaarlijks te verlengen voor €490,00
				 */
				'19': () => LocalizedString
			}
			/**
			 * Leertraject
			 */
			traject: () => LocalizedString
			/**
			 * Inschrijven voor Leertraject
			 */
			subscribe_to_session: () => LocalizedString
			/**
			 * Tweedaagse Masterclass
			 */
			two_day: () => LocalizedString
			/**
			 * Masterclass
			 */
			masterclass: () => LocalizedString
			/**
			 * 12 maanden toegang
			 */
			access_time: () => LocalizedString
			/**
			 * Trixolutions / Lencioni Hybride Teamcoaching Leertraject
			 */
			title: () => LocalizedString
			intro: {
				content: {
					/**
					 * Jouw <strong>hybride Lencioni Leertraject</strong> om je, via <strong>online en fysieke leermomenten</strong>, 
					 */
					'0': () => LocalizedString
					/**
					 * te verdiepen en <strong>bekwamen als Lencioni Teamcoach</strong>, is klaar.<br/>
					 */
					'1': () => LocalizedString
					/**
					 * <br/>
					 */
					'2': () => LocalizedString
					/**
					 * Trixolutions werkt al 15 jaar intensief met alle modellen, methodieken 
					 */
					'3': () => LocalizedString
					/**
					 * en inzichten van The Table Group van Patrick Lencioni. <br/>
					 */
					'4': () => LocalizedString
					/**
					 * Als enige in de Benelux zijn we ook gecertificeerde partner (CAPAPro) 
					 */
					'5': () => LocalizedString
					/**
					 * van Patrick Lencioni. Dit wil zeggen dat we wekelijks <strong>door Patrick zelf 
					 */
					'6': () => LocalizedString
					/**
					 * getraind en gecoached worden</strong> in de vele modellen, assessments en oefeningen, 
					 */
					'7': () => LocalizedString
					/**
					 * en in de Table Group CAPAPro Academy toegang hebben tot honderden filmpjes, 
					 */
					'8': () => LocalizedString
					/**
					 * virtuele trainingen, speciale podcasts, facilitator instructies, etc.<br/>
					 */
					'9': () => LocalizedString
					/**
					 * <br/>
					 */
					'10': () => LocalizedString
					/**
					 * We hebben alle onze Lencioni wijsheid en kennis in <strong>2 mogelijke 
					 */
					'11': () => LocalizedString
					/**
					 * leertrajecten</strong> gegoten:
					 */
					'12': () => LocalizedString
				}
			}
			basic: {
				/**
				 * Zonder
				 */
				title: () => LocalizedString
				intro: {
					/**
					 * Dit leertraject raden we aan als je al redelijk goed met de Piramide aan de slag 
					 */
					'0': () => LocalizedString
					/**
					 * kan en vooral naar verdieping en extra inspiratie zoekt op vlak van zijn assessments, 
					 */
					'1': () => LocalizedString
					/**
					 * speciale oefeningen, bruggen met andere modellen, podcasts, Lencioni filmpjes….<br/>
					 */
					'2': () => LocalizedString
					/**
					 * Dit is de 'do it yourself' aanpak, wél met een uur coaching van onze Trixolutions/Lencioni 
					 */
					'3': () => LocalizedString
					/**
					 * expert inbegrepen.<br/>
					 */
					'4': () => LocalizedString
					/**
					 * Wil je daarna toch wel meedoen aan de tweedaagse Masterclass? Dat kan! Enkel het verschil 
					 */
					'5': () => LocalizedString
					/**
					 * in prijs rekenen we dan aan.
					 */
					'6': () => LocalizedString
				}
				features: {
					'0': {
					}
					'1': {
					}
					'2': {
					}
					'3': {
					}
					'4': {
					}
					'5': {
					}
					'6': {
					}
					'7': {
					}
					'8': {
					}
					'9': {
					}
					'10': {
					}
					'11': {
					}
					'12': {
					}
					'13': {
					}
					'14': {
					}
					'15': {
					}
					'16': {
					}
					'17': {
					}
					'18': {
					}
					'19': {
					}
				}
			}
			full: {
				/**
				 * Met
				 */
				title: () => LocalizedString
				intro: {
					/**
					 * Dit extensieve leertraject raden we aan als je geen of een beperkte kennis van de Piramide 
					 */
					'0': () => LocalizedString
					/**
					 * van Lencioni hebt.<br/>
					 */
					'1': () => LocalizedString
					/**
					 * We gaan immers in detail door het Lencioni Werkboek en leren je een Lencioni traject opbouwen 
					 */
					'2': () => LocalizedString
					/**
					 * en uitrollen, verdiepende kennis en oefeningen in de verschillende lagen van de Piramide, hoe 
					 */
					'3': () => LocalizedString
					/**
					 * de assessments in te zetten.<br/>
					 */
					'4': () => LocalizedString
					/**
					 * In deze module zit ook een uur opvolgcoaching inbegrepen, alsook 15 Lencioni Piramides én een 
					 */
					'5': () => LocalizedString
					/**
					 * Trixolutions/Lencioni Certificaat!
					 */
					'6': () => LocalizedString
				}
				features: {
					'0': {
					}
					'1': {
					}
					'2': {
					}
					'3': {
					}
					'4': {
					}
					'5': {
					}
					'6': {
					}
					'7': {
					}
					'8': {
					}
					'9': {
					}
					'10': {
					}
					'11': {
					}
					'12': {
					}
					'13': {
					}
					'14': {
					}
					'15': {
					}
					'16': {
					}
					'17': {
					}
					'18': {
					}
					'19': {
					}
				}
			}
		}
	}
	components: {
		open_sessions_accordeon: {
			first: {
				/**
				 * Het Partnership tussen Trixolutions en Patrick Lencioni
				 */
				title: () => LocalizedString
				/**
				 * Trixolutions is als enige in de Benelux lid van de Table Group van Patrick Lencioni. (CAPA Pro)
				 */
				content_title: () => LocalizedString
				first: {
					/**
					 * We worden in de Lencioni CAPA Pro Academy op wekelijkse basis begeleid, gecoacht en 
					 */
					'0': () => LocalizedString
					/**
					 * getraind in de verschillende Lencioni modellen, assessment en toepassingen door 
					 */
					'1': () => LocalizedString
					/**
					 * Patrick Lencioni en zijn consultants zelf.<br/>
					 */
					'2': () => LocalizedString
					/**
					 * Deze kennis, gecombineerd met meer dan 200 teamtrajecten op de teller, zijn we de 
					 */
					'3': () => LocalizedString
					/**
					 * ideale partner om jouw Lencioni kennis te verhogen naar het hoogste niveau.
					 */
					'4': () => LocalizedString
				}
				/**
				 * Niet de operationele en strategische sterktes van een team zijn doorslaggevend … maar wel de kracht en gezondheid van dit team zullen hét ultieme competitief voordeel zijn in de toekomst …
				 */
				quote: () => LocalizedString
				last: {
					/**
					 * De kracht van een gezond team zit voornamelijk in de vaardigheid van teamleden 
					 */
					'0': () => LocalizedString
					/**
					 * om <strong>vertrouwen</strong> op te bouwen, met elkaar <strong>respectvolle conflicten</strong> te kunnen hebben, 
					 */
					'1': () => LocalizedString
					/**
					 * <strong>betrokkenheid bij het team</strong> te voelen, elkaar <strong>aansprakelijk</strong> te durven stellen en 
					 */
					'2': () => LocalizedString
					/**
					 * <strong>resultaatgericht</strong> te kunnen werken.
					 */
					'3': () => LocalizedString
				}
			}
			second: {
				/**
				 * Welke Vragen zullen We voor Je Oplossen?
				 */
				title: () => LocalizedString
				/**
				 * In deze opleiding zal je antwoorden vinden op vragen als
				 */
				content_title: () => LocalizedString
				/**
				 * Deze teamcoaching opleiding zal je antwoord geven op vragen als:
				 */
				list_title: () => LocalizedString
				list: {
					/**
					 * Hoe werk ik aan een gezonde teamcultuur met dit model?
					 */
					'0': () => LocalizedString
					/**
					 * Hoe verkoop ik een Lencioni traject aan mijn (interne) klant?
					 */
					'1': () => LocalizedString
					/**
					 * Hoe creëer ik voldoende 'goesting' of 'burning platform' om een Lencioni traject te starten?
					 */
					'2': () => LocalizedString
					/**
					 * Hoe ontwikkel ik een Lencioni teamcoaching traject?
					 */
					'3': () => LocalizedString
					/**
					 * Wat zijn de verschillende stappen in een Lencioni teamcoachingstraject?
					 */
					'4': () => LocalizedString
					/**
					 * Welke Lencioni oefeningen zijn er (extra) om met teams in de verschillende lagen van de Piramide te werk te gaan?
					 */
					'5': () => LocalizedString
					/**
					 * Met welke andere “modellen” kan de Piramide gecombineerd worden?
					 */
					'6': () => LocalizedString
					/**
					 * Hoe zet ik het volledige Lencioni Team Assessment juist in?
					 */
					'7': () => LocalizedString
					/**
					 * Hoe gebruik ik het Lencioni Persoonlijk Teamlid Assessment?
					 */
					'8': () => LocalizedString
					/**
					 * Welke vaardigheden heeft een Lencioni Teamcoach juist nodig?
					 */
					'9': () => LocalizedString
					/**
					 * Welke Lencioni Tools en materiaal is er en kan ik inzetten?
					 */
					'10': () => LocalizedString
					/**
					 * Waar kan ik hulp vinden als ik vastloop in een teamtraject?
					 */
					'11': () => LocalizedString
					/**
					 * ...
					 */
					'12': () => LocalizedString
				}
			}
		}
	}
}

export type Formatters = {}
