// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters.js'
import type { Locales, Translations } from './i18n-types.js'
import { loadedFormatters, loadedLocales, locales } from './i18n-util.js'

import en from './en/index.js'
import fr from './fr/index.js'
import nl from './nl/index.js'

import en_components from './en/components/index.js'
import en_nav from './en/nav/index.js'
import en_other from './en/other/index.js'
import en_pages from './en/pages/index.js'
import en_pages_explore from './en/pages_explore/index.js'
import en_sessions from './en/sessions/index.js'
import fr_components from './fr/components/index.js'
import fr_nav from './fr/nav/index.js'
import fr_other from './fr/other/index.js'
import fr_pages from './fr/pages/index.js'
import fr_pages_explore from './fr/pages_explore/index.js'
import fr_sessions from './fr/sessions/index.js'
import nl_components from './nl/components/index.js'
import nl_nav from './nl/nav/index.js'
import nl_other from './nl/other/index.js'
import nl_pages from './nl/pages/index.js'
import nl_pages_explore from './nl/pages_explore/index.js'
import nl_sessions from './nl/sessions/index.js'

const localeTranslations = {
	en: {
		...en,
		components: en_components,
		nav: en_nav,
		other: en_other,
		pages: en_pages,
		pages_explore: en_pages_explore,
		sessions: en_sessions
	},
	fr: {
		...fr,
		components: fr_components,
		nav: fr_nav,
		other: fr_other,
		pages: fr_pages,
		pages_explore: fr_pages_explore,
		sessions: fr_sessions
	},
	nl: {
		...nl,
		components: nl_components,
		nav: nl_nav,
		other: nl_other,
		pages: nl_pages,
		pages_explore: nl_pages_explore,
		sessions: nl_sessions
	},
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
